export const Permissions = {
  createAdministrasiUmum: 'create:AdministrasiUmum',
  deleteAdministrasiUmum: 'delete:AdministrasiUmum',
  readAdministrasiUmum: 'read:AdministrasiUmum',
  updateAdministrasiUmum: 'update:AdministrasiUmum',
  createBooking: 'create:Booking',
  deleteBooking: 'delete:Booking',
  readBooking: 'read:Booking',
  updateBooking: 'update:Booking',
  createCheckIn: 'create:CheckIn',
  deleteCheckIn: 'delete:CheckIn',
  readCheckIn: 'read:CheckIn',
  updateCheckIn: 'update:CheckIn',
  readDashboard: 'read:Dashboard',
  createDrugInventory: 'create:DrugInventory',
  deleteDrugInventory: 'delete:DrugInventory',
  readDrugInventory: 'read:DrugInventory',
  updateDrugInventory: 'update:DrugInventory',
  createExamination: 'create:Examination',
  deleteExamination: 'delete:Examination',
  readExamination: 'read:Examination',
  updateExamination: 'update:Examination',
  createRegistration: 'create:Registration',
  deleteRegistration: 'delete:Registration',
  readRegistration: 'read:Registration',
  updateRegistration: 'update:Registration',
};
